config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root Route
  root to: "main#index"

  # About us Route
  get "about-us", to: "about#index", as: :about

  # Sign Up Route
  get "sign-up", to: "registrations#new"
  post "sign-up", to: "registrations#create"

  # Sign In Route
  get "sign-in", to: "session#new"
  post "sign-in", to: "session#create"

  # Logout Route
  delete "logout", to: "session#destroy"

  # Password
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "home", to: "thought#index", as: :home
  post "thought/post/", to: "thought#create"

  post "thought/:id/like", to: "like#create", as: :like

  post "api/auth", to: "auth#login", as: :api_auth
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
            # send mail
            # deliver_later -> send email using background job
            # deliver_now -> send email rigth away and send a response in rails app browser slower
            # because it has to wait email is actually sent
            PasswordMailer.with(user: @user).reset.deliver_now
            redirect_to root_path, notice: "We have sent a link to your email for reset your password."
        else
            flash[:alert] = "The e-mail address is not assigned to any user account"
            render :new
        end
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        #
        # redirect if token has expired
        redirect_to sign_in_path, alert: "Your token has expired, Please try again."
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
        else
            render :edit
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/views/password_resets/edit.html.erb
<h1>Reset Your Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
    <% @user.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
  </div>
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "Example: arifbintoro@mailinator.com" %>
  </div>
  <div>
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>