config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root Route
  root to: "main#index"

  # About us Route
  get "about-us", to: "about#index", as: :about

  # Sign Up Route
  get "sign-up", to: "registrations#new"
  post "sign-up", to: "registrations#create"

  # Sign In Route
  get "sign-in", to: "session#new"
  post "sign-in", to: "session#create"

  # Logout Route
  delete "logout", to: "session#destroy"

  # Password
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "home", to: "thought#index", as: :home
  post "thought/post/", to: "thought#create"

  post "thought/:id/like", to: "like#create", as: :like

  post "api/auth", to: "auth#login", as: :api_auth
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
    end

    # perform sign up
    # find user by email, if it's present and authenticated using params[:password] then,
    # set session[:user_id] to user.id and redirect to root path
    # if user not present or user not authenticated
    # render to new function
    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Successfuly sign in"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end


    # logout function
    # set session[:user_id] to nil
    # and redirect to root_path
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out"
    end
end

app/views/session/new.html.erb
<h1>Sign In</h1>

<%= form_with url: sign_in_path do |form| %>
    <div class="mb-3">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control", placeholder: "Example: arifbintoro@mailinator.com" %>
    </div>
    <div class="mb-3">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
      <%= link_to "Forgot your password?", password_reset_path %>
    </div>

    <div>
      <%= form.submit "Sign In", class: "btn btn-primary" %>
    </div>
<% end %>