config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root Route
  root to: "main#index"

  # About us Route
  get "about-us", to: "about#index", as: :about

  # Sign Up Route
  get "sign-up", to: "registrations#new"
  post "sign-up", to: "registrations#create"

  # Sign In Route
  get "sign-in", to: "session#new"
  post "sign-in", to: "session#create"

  # Logout Route
  delete "logout", to: "session#destroy"

  # Password
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "home", to: "thought#index", as: :home
  post "thought/post/", to: "thought#create"

  post "thought/:id/like", to: "like#create", as: :like

  post "api/auth", to: "auth#login", as: :api_auth
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger show mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" =%>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span><%= Current.user.email %></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Edit Password", edit_password_path, class: "dropdown-item" %>
              <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", sign_in_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>