config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root Route
  root to: "main#index"

  # About us Route
  get "about-us", to: "about#index", as: :about

  # Sign Up Route
  get "sign-up", to: "registrations#new"
  post "sign-up", to: "registrations#create"

  # Sign In Route
  get "sign-in", to: "session#new"
  post "sign-in", to: "session#create"

  # Logout Route
  delete "logout", to: "session#destroy"

  # Password
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "home", to: "thought#index", as: :home
  post "thought/post/", to: "thought#create"

  post "thought/:id/like", to: "like#create", as: :like

  post "api/auth", to: "auth#login", as: :api_auth
end

app/models/thought.rb
class Thought < ApplicationRecord
  belongs_to :user

  has_many :like

  validates :idea, presence: true

  def posted_at
    posted = (Time.now - self[:created_at]) / 3600
    if posted < 24 && posted > 1
      return "%dh ago" % [posted.to_i]
    elsif posted < 1 && posted > 0
      posted = posted * 60
      return "%dm ago" % [posted.to_i]
    elsif posted > 24 && posted < 48
      return "Yesterday"
    else
      return self[:created_at].strf("%d %b %Y")
    end
  end
end

app/controllers/thought_controller.rb
class ThoughtController < ApplicationController
    before_action :login_required

    def index
        @thoughts = Thought.where({"user" => Current.user}).order(created_at: :desc)
    end

    def create
        thought = Thought.new(idea: params[:idea], user: Current.user)
        if thought.save
            redirect_to home_path
        end
    end
end

app/views/thought/index.html.erb
<%= form_with url: thought_post_path do |form|%>
  <div class="mb-3">
    <%= form.label :idea %>
    <%= form.text_area :idea, size: "70x5", class: "form-control", placeholder: "Share your Idea...", :maxlength => 200 %>
  </div>

  <div class="d-flex align-items-center justify-content-end">
    <%= form.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

<div class="border-top border-2 my-4 py-4">
  <% @thoughts.each do |thought| %>
    <div class="card mb-2">
      <div class="card-body">
        <h6 class="card-title">Idea shared by <%= thought.user.email %></h5>
        <p class="card-subtitle mb-2 text-muted border-bottom" style="font-size: 11px;"><%= thought.posted_at %></p>
        <p class="card-text"><%= thought.idea %></p>
        <%= link_to like_path(thought.id), method: :post, class: "card-link btn btn-outline-link", id: "like-button", remote: true do %>
          <% if thought.like.present? %>
            <%= thought.like.count %>
          <% end %>
          <%= fa_icon "heart" %>
        <% end %>
        <a href="#" class="card-link btn btn-outline-link"><i class="far fa-comment"></i></a>
      </div> 
    </div>
  <% end %>
</div>